name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: release.sh
      uses: dante-ev/latex-action@latest
      with:
        entrypoint: make

    - name: Store pdf
      uses: actions/upload-artifact@v2
      with:
        path: '*/output/*.pdf'


