name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install pdflatex
      run: apt install pdflatex

    - name: Make 
      run: make

    - name: Store pdf
      uses: actions/upload-artifact@v2
      with:
        path: '*/output/*.pdf'


